name: Switch Post Runner

on:
  workflow_dispatch:
  schedule:
    # Runs ~8:30 PM NZST / 9:30 PM NZDT on Mondays, Wednesdays, and Saturdays (08:30 UTC same day)
    - cron: "30 8 * * 1,3,6"

concurrency:
  group: switch-post
  cancel-in-progress: true

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      PLATFORM: switch
      FB_PAGE_ACCESS_TOKEN_TEST: ${{ secrets.FB_PAGE_ACCESS_TOKEN_TEST }}
      FB_PAGE_ACCESS_TOKEN_LIVE: ${{ secrets.FB_PAGE_ACCESS_TOKEN_LIVE }}
      CACHE_PREFIX: switch-data-v1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests pillow
          fi

      # --- Restore persisted JSONs (use latest with prefix) ---
      - name: Restore export tracker & force list (switch)
        uses: actions/cache/restore@v4
        with:
          path: |
            trackers/already_exported_switch.json
            force/force_include_switch.json
          key: ${{ env.CACHE_PREFIX }}-${{ github.run_id }}
          restore-keys: |
            ${{ env.CACHE_PREFIX }}-

      # --- Chain your scripts ---
      - name: 1) Build trending JSON
        run: python getTrend.py "$PLATFORM"

      - name: 2) Enrich with screenshots
        env:
          IGDB_CLIENT_ID: ${{ secrets.IGDB_CLIENT_ID }}
          IGDB_CLIENT_SECRET: ${{ secrets.IGDB_CLIENT_SECRET }}
        run: python getScreenshots.py "$PLATFORM"

      - name: 3) Generate images
        run: python generateImage.py "$PLATFORM"

      - name: 4) Post to Facebook
        run: python facebookPost.py "$PLATFORM"

      # --- Ensure files exist so cache save never fails ---
      - name: Ensure persisted files exist (switch)
        if: always()
        run: |
          [ -f trackers/already_exported_switch.json ] || : > trackers/already_exported_switch.json
          [ -f force/force_include_switch.json ] || : > force/force_include_switch.json

      # --- Save updated JSONs with a unique key (no collisions) ---
      - name: Save export tracker & force list (switch)
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            trackers/already_exported_switch.json
            force/force_include_switch.json
          key: ${{ env.CACHE_PREFIX }}-${{ github.run_id }}


      # --- (optional) Show tracker contents in logs ---
      - name: Show tracker JSON (switch)
        if: always()
        run: |
          echo "== trackers/already_exported_switch.json =="
          if [ -f trackers/already_exported_switch.json ]; then
            cat trackers/already_exported_switch.json
          else
            echo "Tracker file not found."
          fi
          echo "== force/force_include_switch.json =="
          if [ -f force/force_include_switch.json ]; then
            cat force/force_include_switch.json
          else
            echo "Force file not found."
          fi

      # --- Upload tracker & force list as artifacts for later download ---
      - name: Upload tracker artifacts (switch)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: switch-tracker-${{ github.run_number }}
          path: |
            trackers/already_exported_switch.json
            force/force_include_switch.json
          if-no-files-found: warn
          retention-days: 7
